import { useSession } from "@/auth/SessionProvider";
import Constants from "expo-constants";
import createClient, { Middleware } from "openapi-fetch";
import { cropsApi } from "./crops.api";
import { farmApi } from "./farms.api";
import { fertilizerSpreadersApi } from "./fertilizerSpreaders.api";
import { fertilizerApplicationsApi } from "./fertilizerApplications.api";
import { fertilizersApi } from "./fertilizers.api";
import { harvestsApi } from "./harvests.api";
import { geoAdminApi } from "./geo-admin";
import { harvestingMachineryApi } from "./harvestingMachinery.api";
import { layersApi } from "./layers.api";
import { parcelsApi } from "./parcels.api";
import { plotsApi } from "./plots.api";
import { userApi } from "./user.api";
import type { paths } from "./v1"; // generated by openapi-typescript
import { cropRotationsApi } from "./crop-rotations.api";
import { tillagesApi } from "./tillages.api";
import { cropProtectionApplicationsApi } from "./cropProtectionApplications.api";
import { tillageEquipmentsApi } from "./tillageEquipment.api";
import { cropProtectionProductsApi } from "./cropProtectionProducts.api";
import { cropProtectionEquipmentsApi } from "./cropProtectionEquipments.api";
import { locale } from "@/locales/i18n";
import { reportsApi } from "./reports.api";

// const baseUrl = "http://localhost:8000/";
const uri =
  Constants.expoConfig?.hostUri?.split(":").shift()?.concat(":8000") ??
  process.env.EXPO_PUBLIC_API_URI;
const baseUrl = `http://${uri}`;

export type FetchClient = typeof client;

const middleware: Middleware = {
  async onResponse({ request, response, options }) {
    if (!response.ok) {
      // Will produce error messages like "https://example.org/api/v1/example: 404 Not Found".
      const content = await response.json();
      throw new Error(
        `${response.url}: ${response.status} - ${content.error.message}`
      );
    }
  },
  async onRequest({ request, options }) {
    request.headers.set("Accept", "application/json");
    request.headers.set("Accept-Language", locale);
  },
};

const client = createClient<paths>({
  baseUrl,
});

client.use(middleware);

const authMiddleware = (token: string): Middleware => ({
  async onRequest({ request, options }) {
    request.headers.set("Authorization", `Bearer ${token}`);
    return request;
  },
});
export function createAuthClient(token: string) {
  const authClient = createClient<paths>({
    baseUrl,
  });
  authClient.use(middleware, authMiddleware(token));
  return authClient;
}

export function useApi() {
  const { token } = useSession();
  if (!token) {
    return api(client);
  }
  const authClient = createAuthClient(token);
  return api(authClient);
}

export function api(client: FetchClient) {
  return {
    layers: layersApi(client),
    farms: farmApi(client),
    users: userApi(client),
    parcels: parcelsApi(client),
    plots: plotsApi(client),
    geoAdmin: geoAdminApi(),
    crops: cropsApi(client),
    cropRotations: cropRotationsApi(client),
    harvestingMachinery: harvestingMachineryApi(client),
    harvests: harvestsApi(client),
    fertilizerApplications: fertilizerApplicationsApi(client),
    fertilizers: fertilizersApi(client),
    fertilizerSpreaders: fertilizerSpreadersApi(client),
    tillages: tillagesApi(client),
    tillageEquipments: tillageEquipmentsApi(client),
    cropProtectionProducts: cropProtectionProductsApi(client),
    cropProtectionApplications: cropProtectionApplicationsApi(client),
    cropProtectionEquipments: cropProtectionEquipmentsApi(client),
    reports: reportsApi(client),
  };
}
