import { useSession } from "@/auth/SessionProvider";
import { supabase } from "@/supabase/supabase";
import Constants from "expo-constants";
import createClient, { Middleware } from "openapi-fetch";
import { animalsApi } from "./animals.api";
import { cropsApi } from "./crops.api";
import { farmApi } from "./farms.api";
import { fertilizerApplicationsApi } from "./fertilizerApplications.api";
import { fertilizerApplicationPresetsApi } from "./fertilizerApplicationPresets.api";
import { fertilizersApi } from "./fertilizers.api";
import { harvestsApi } from "./harvests.api";
import { geoAdminApi } from "./geo-admin";
import { harvestPresetsApi } from "./harvestPresets.api";
import { layersApi } from "./layers.api";
import { plotsApi } from "./plots.api";
import { userApi } from "./user.api";
import type { paths } from "./v1"; // generated by openapi-typescript
import { cropRotationsApi } from "./crop-rotations.api";
import { tillagesApi } from "./tillages.api";
import { tillagePresetsApi } from "./tillagePresets.api";
import { cropProtectionApplicationsApi } from "./cropProtectionApplications.api";
import { cropProtectionProductsApi } from "./cropProtectionProducts.api";
import { cropProtectionApplicationPresetsApi } from "./cropProtectionApplicationPresets.api";
import { earTagsApi } from "./earTags.api";
import i18n from "@/locales/i18n";
import { reportsApi } from "./reports.api";
import { drugsApi } from "./drugs.api";
import { treatmentsApi } from "./treatments.api";
import { cropFamiliesApi } from "./crop-families.api";
import { herdsApi } from "./herds.api";
import { outdoorJournalApi } from "./outdoor-journal.api";
import { fieldEventsApi } from "./field-events.api";
import { wikiApi } from "./wiki.api";
import { tasksApi } from "./tasks.api";
import { membershipApi } from "./membership.api";
import { animalJournalApi } from "./animal-journal.api";
import { plotJournalApi } from "./plot-journal.api";
import { donationsApi } from "./donations.api";

const apiUrl = process.env.EXPO_PUBLIC_API_URL;
// const baseUrl = "http://localhost:8000/";
const localUrl = `http://${Constants.expoConfig?.hostUri?.split(":").shift()?.concat(":8000")}`;

const baseUrl = apiUrl ?? localUrl;

export type FetchClient = typeof client;

// Deduped so a burst of parallel 401s (e.g. every active query failing around
// the same time because the session is genuinely dead) only triggers one
// refresh call instead of one per failed request.
let refreshInFlight: ReturnType<typeof supabase.auth.refreshSession> | null =
  null;

function triggerTokenRefresh() {
  if (!refreshInFlight) {
    refreshInFlight = supabase.auth.refreshSession().finally(() => {
      refreshInFlight = null;
    });
  }
}

const middleware: Middleware = {
  async onResponse({ request, response, options }) {
    if (!response.ok) {
      if (response.status === 401) {
        // Recovers a merely-stale session for the next request, or — if the
        // refresh token itself is dead — auth-js's own _callRefreshToken
        // removes the session and emits SIGNED_OUT, which SessionProvider
        // already turns into token=null, routing back to the auth stack.
        triggerTokenRefresh();
      }
      const content = await response.json();
      throw new Error(`${response.url}: ${response.status} - ${content.error}`);
    }
  },
  async onRequest({ request, options }) {
    request.headers.set("Accept", "application/json");
    request.headers.set("Accept-Language", i18n.language);
  },
};

const client = createClient<paths>({
  baseUrl,
});

client.use(middleware);

const authMiddleware = (token: string): Middleware => ({
  async onRequest({ request, options }) {
    request.headers.set("Authorization", `Bearer ${token}`);
    return request;
  },
});

// The active farm id lives here, outside React state, on purpose. It's read by
// farmMiddleware at the moment each request is actually sent — not by any hook at render
// time — so it can never be a stale value captured by a component that hasn't re-rendered
// yet. ActiveFarmContext (features/farms/ActiveFarmContext.tsx) is the sole writer, via
// setActiveFarmIdForRequests, whenever the selection changes.
let currentActiveFarmId: string | null = null;

export function setActiveFarmIdForRequests(farmId: string | null) {
  currentActiveFarmId = farmId;
}

// x-farm-id is not part of the OpenAPI spec (the backend reads it manually in its auth
// middleware), so it's attached by hand here rather than via generated request typing.
const farmMiddleware: Middleware = {
  async onRequest({ request, options }) {
    if (currentActiveFarmId) {
      request.headers.set("x-farm-id", currentActiveFarmId);
    }
    return request;
  },
};

export function createAuthClient(token: string) {
  const authClient = createClient<paths>({
    baseUrl,
  });
  authClient.use(middleware, authMiddleware(token), farmMiddleware);
  return authClient;
}

export function useApi() {
  const { token } = useSession();
  if (!token) {
    return api(client);
  }
  const authClient = createAuthClient(token);
  return api(authClient);
}

export function api(client: FetchClient) {
  return {
    animals: animalsApi(client),
    earTags: earTagsApi(client),
    drugs: drugsApi(client),
    treatments: treatmentsApi(client),
    layers: layersApi(client),
    farms: farmApi(client),
    users: userApi(client),
    plots: plotsApi(client),
    geoAdmin: geoAdminApi(),
    crops: cropsApi(client),
    cropFamilies: cropFamiliesApi(client),
    cropRotations: cropRotationsApi(client),
    harvestPresets: harvestPresetsApi(client),
    harvests: harvestsApi(client),
    fertilizerApplications: fertilizerApplicationsApi(client),
    fertilizerApplicationPresets: fertilizerApplicationPresetsApi(client),
    fertilizers: fertilizersApi(client),
    tillages: tillagesApi(client),
    tillagePresets: tillagePresetsApi(client),
    cropProtectionProducts: cropProtectionProductsApi(client),
    cropProtectionApplications: cropProtectionApplicationsApi(client),
    cropProtectionApplicationPresets:
      cropProtectionApplicationPresetsApi(client),
    reports: reportsApi(client),
    herds: herdsApi(client),
    outdoorJournal: outdoorJournalApi(client),
    fieldEvents: fieldEventsApi(client),
    wiki: wikiApi(client),
    tasks: tasksApi(client),
    membership: membershipApi(client),
    animalJournal: animalJournalApi(client),
    plotJournal: plotJournalApi(client),
    donations: donationsApi(client),
  };
}
