import { useSession } from "@/auth/SessionProvider";
import Constants from "expo-constants";
import createClient, { Middleware } from "openapi-fetch";
import { animalsApi } from "./animals.api";
import { cropsApi } from "./crops.api";
import { farmApi } from "./farms.api";
import { fertilizerApplicationsApi } from "./fertilizerApplications.api";
import { fertilizerApplicationPresetsApi } from "./fertilizerApplicationPresets.api";
import { fertilizersApi } from "./fertilizers.api";
import { harvestsApi } from "./harvests.api";
import { geoAdminApi } from "./geo-admin";
import { harvestPresetsApi } from "./harvestPresets.api";
import { layersApi } from "./layers.api";
import { plotsApi } from "./plots.api";
import { userApi } from "./user.api";
import type { paths } from "./v1"; // generated by openapi-typescript
import { cropRotationsApi } from "./crop-rotations.api";
import { tillagesApi } from "./tillages.api";
import { tillagePresetsApi } from "./tillagePresets.api";
import { cropProtectionApplicationsApi } from "./cropProtectionApplications.api";
import { cropProtectionProductsApi } from "./cropProtectionProducts.api";
import { cropProtectionApplicationPresetsApi } from "./cropProtectionApplicationPresets.api";
import { earTagsApi } from "./earTags.api";
import { locale } from "@/locales/i18n";
import { reportsApi } from "./reports.api";
import { drugsApi } from "./drugs.api";
import { treatmentsApi } from "./treatments.api";
import { cropFamiliesApi } from "./crop-families.api";
import { herdsApi } from "./herds.api";
import { outdoorJournalApi } from "./outdoor-journal.api";
import { fieldEventsApi } from "./field-events.api";
import { wikiApi } from "./wiki.api";

const apiUrl = process.env.EXPO_PUBLIC_API_URL;
// const baseUrl = "http://localhost:8000/";
const localUrl = `http://${Constants.expoConfig?.hostUri?.split(":").shift()?.concat(":8000")}`;

const baseUrl = apiUrl ?? localUrl;

export type FetchClient = typeof client;

const middleware: Middleware = {
  async onResponse({ request, response, options }) {
    if (!response.ok) {
      const content = await response.json();
      throw new Error(`${response.url}: ${response.status} - ${content.error}`);
    }
  },
  async onRequest({ request, options }) {
    request.headers.set("Accept", "application/json");
    request.headers.set("Accept-Language", locale);
  },
};

const client = createClient<paths>({
  baseUrl,
});

client.use(middleware);

const authMiddleware = (token: string): Middleware => ({
  async onRequest({ request, options }) {
    request.headers.set("Authorization", `Bearer ${token}`);
    return request;
  },
});
export function createAuthClient(token: string) {
  const authClient = createClient<paths>({
    baseUrl,
  });
  authClient.use(middleware, authMiddleware(token));
  return authClient;
}

export function useApi() {
  const { token } = useSession();
  if (!token) {
    return api(client);
  }
  const authClient = createAuthClient(token);
  return api(authClient);
}

export function api(client: FetchClient) {
  return {
    animals: animalsApi(client),
    earTags: earTagsApi(client),
    drugs: drugsApi(client),
    treatments: treatmentsApi(client),
    layers: layersApi(client),
    farms: farmApi(client),
    users: userApi(client),
    plots: plotsApi(client),
    geoAdmin: geoAdminApi(),
    crops: cropsApi(client),
    cropFamilies: cropFamiliesApi(client),
    cropRotations: cropRotationsApi(client),
    harvestPresets: harvestPresetsApi(client),
    harvests: harvestsApi(client),
    fertilizerApplications: fertilizerApplicationsApi(client),
    fertilizerApplicationPresets: fertilizerApplicationPresetsApi(client),
    fertilizers: fertilizersApi(client),
    tillages: tillagesApi(client),
    tillagePresets: tillagePresetsApi(client),
    cropProtectionProducts: cropProtectionProductsApi(client),
    cropProtectionApplications: cropProtectionApplicationsApi(client),
    cropProtectionApplicationPresets: cropProtectionApplicationPresetsApi(client),
    reports: reportsApi(client),
    herds: herdsApi(client),
    outdoorJournal: outdoorJournalApi(client),
    fieldEvents: fieldEventsApi(client),
    wiki: wikiApi(client),
  };
}
